# Generated by Django 4.2.4 on 2023-08-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('cmpnm', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('fileimage', models.FileField(upload_to='djangoapp/static')),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pro_cmpny', models.CharField(max_length=30)),
                ('quan', models.IntegerField()),
                ('expdt', models.DateField()),
                ('descrp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
