# Generated by Django 4.2.4 on 2023-08-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_file_upload2'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioname', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='djangoapp/static')),
                ('vedioname', models.CharField(max_length=50)),
                ('vedio', models.FileField(upload_to='djangoapp/static')),
                ('pdfname', models.CharField(max_length=40)),
                ('pdf', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
    ]
