# Generated by Django 4.2.4 on 2023-08-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_file_upload3'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('TamilNadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka')], max_length=30)),
                ('tamil', models.BooleanField(default=False)),
                ('malayalam', models.BooleanField(default=False)),
                ('english', models.BooleanField(default=False)),
            ],
        ),
    ]
