# Generated by Django 4.2.4 on 2023-10-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_regmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regmodel',
        ),
    ]
